[package]
name = "swc-plugin-inline-constants"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
lazy_static = "1.4.0"
serde = "1"
serde_json = "1.0.111"
swc_core = { version = "0.86.*", features = ["ecma_plugin_transform"] }
swc_ecma_utils = "0.125.4"
swc_ecma_visit = { version = "0.96.*" }
swc_visit = "0.5.8"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
